# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 171f36c61fead66f63db8b13e6a6c7bebdd540373772d6e11a5ffb3a00b50a73e6e5c4af478c52f78cdd563200c21ee461523d88fe3be906119f9fd6d4e67b62

test:
  secret_key_base: 45979849b225d595354a0ef0518d270dc0816b5e2f0cafca1ae4804ae8f26a9e08903869a73626fcdc1f1884d2e013701b6d2075f53a3d3a9292e9b0432674c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
